CREATE TYPE website_type AS ENUM ('technology', 'popular');

CREATE TABLE website_contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type website_type NOT NULL,
  company TEXT NOT NULL,
  country TEXT NOT NULL,
  details TEXT,
  email TEXT NOT NULL UNIQUE,
  first TEXT NOT NULL,
  last TEXT NOT NULL,
  phone TEXT,
  size INT,
  title TEXT,
  website TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE website_contacts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable public insert" ON website_contacts FOR INSERT WITH CHECK (true);

CREATE TABLE websites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  type website_type NOT NULL,
  category TEXT NOT NULL,
  developer TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  logo TEXT NOT NULL,
  images TEXT[],
  overview TEXT NOT NULL,
  website TEXT NOT NULL,
  docs TEXT NOT NULL,
  contact BIGINT REFERENCES website_contacts NOT NULL,
  approved BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  tsv TSVECTOR GENERATED ALWAYS AS (
    setweight(to_tsvector('english', title), 'A') ||
    setweight(to_tsvector('english', description), 'B') ||
    setweight(to_tsvector('english', overview), 'C') ||
    setweight(to_tsvector('english', category), 'D') ||
    setweight(to_tsvector('english', slug), 'D')
  ) STORED
);

ALTER TABLE websites ENABLE ROW LEVEL SECURITY;