import os
import dotenv
from sqlalchemy import create_engine, text

def database_connection_url():
    dotenv.load_dotenv()
    return os.getenv("POSTGRES_URI")

engine = create_engine(database_connection_url(), pool_pre_ping=True)

# testing out the connection with a simple query
try:
    with engine.connect() as connection:
        result = connection.execute(text("SELECT table_name FROM information_schema.tables WHERE table_schema = 'public'"))
        print("Tables in the 'public' schema:")
        for row in result:
            print(row[0])
except Exception as e:
    print("Database connection failed:", e)

websites = [
    "google.com",
    "youtube.com",
    "reddit.com",
    "amazon.com",
    "facebook.com",
    "duckduckgo.com",
    "yahoo.com",
    "wikipedia.org",
    "twitter.com",
    "instagram.com",
    "bing.com",
    "fandom.com",
    "weather.com",
    "cnn.com",
    "espn.com",
    "tiktok.com",
    "nytimes.com",
    "foxnews.com",
    "ebay.com",
    "quora.com",
    "microsoftonline.com",
    "walmart.com",
    "linkedin.com",
    "office.com",
    "imdb.com",
    "openai.com",
    "live.com",
    "twitch.tv",
    "microsoft.com",
    "usps.com",
    "dailymail.co.uk",
    "netflix.com",
    "msn.com",
    "etsy.com",
    "instructure.com",
    "paypal.com",
    "bestbuy.com",
    "zoom.us",
    "nypost.com",
    "accuweather.com",
    "pinterest.com",
    "indeed.com",
    "zillow.com",
    "apple.com",
    "homedepot.com",
    "discord.com",
    "bbc.com",
    "ign.com",
    "ups.com",
    "sharepoint.com",
    "target.com",
    "imgur.com",
    "craigslist.org",
    "spotify.com",
    "fedex.com",
    "amazonaws.com",
    "gamespot.com",
    "breitbart.com",
    "patreon.com",
    "washingtonpost.com",
    "hulu.com",
    "theguardian.com",
    "costco.com",
    "chase.com",
    "steamcommunity.com",
    "outlook.com",
    "slickdeals.net",
    "roblox.com",
    "github.com",
    "usatoday.com",
    "samsung.com",
    "character.ai",
    "capitalone.com",
    "temu.com",
    "nextdoor.com",
    "lowes.com",
    "nih.gov",
    "yelp.com",
    "foxbusiness.com",
    "npr.org",
    "canva.com",
    "xfinity.com",
    "quizlet.com",
    "steampowered.com",
    "okta.com",
    "nbcnews.com",
    "cnbc.com",
    "apnews.com",
    "adobe.com",
    "cvs.com",
    "wordpress.com",
    "whatsapp.com",
]

websites_info = [
    {"url": "google.com", "site_name": "Google", "category": "Search Engine", "tos_url": "https://policies.google.com/terms?hl=en-US"},
    {"url": "youtube.com", "site_name": "YouTube", "category": "Video Sharing", "tos_url": ""},
    {"url": "reddit.com", "site_name": "Reddit", "category": "Social News", "tos_url": ""},
    {"url": "amazon.com", "site_name": "Amazon", "category": "E-commerce", "tos_url": ""},
    {"url": "facebook.com", "site_name": "Facebook", "category": "Social Networking", "tos_url": ""},
    {"url": "duckduckgo.com", "site_name": "DuckDuckGo", "category": "Search Engine", "tos_url": ""},
    {"url": "yahoo.com", "site_name": "Yahoo", "category": "Web Services", "tos_url": ""},
    {"url": "wikipedia.org", "site_name": "Wikipedia", "category": "Online Encyclopedia", "tos_url": ""},
    {"url": "twitter.com", "site_name": "Twitter", "category": "Social Networking", "tos_url": ""},
    {"url": "instagram.com", "site_name": "Instagram", "category": "Social Networking", "tos_url": ""},
    {"url": "bing.com", "site_name": "Bing", "category": "Search Engine", "tos_url": ""},
    {"url": "fandom.com", "site_name": "Fandom", "category": "Fan Community", "tos_url": ""},
    {"url": "weather.com", "site_name": "The Weather Channel", "category": "Weather", "tos_url": ""},
    {"url": "cnn.com", "site_name": "CNN", "category": "News", "tos_url": ""},
    {"url": "espn.com", "site_name": "ESPN", "category": "Sports", "tos_url": ""},
    {"url": "tiktok.com", "site_name": "TikTok", "category": "Social Networking", "tos_url": ""},
    {"url": "nytimes.com", "site_name": "The New York Times", "category": "News", "tos_url": ""},
    {"url": "foxnews.com", "site_name": "Fox News", "category": "News", "tos_url": ""},
    {"url": "ebay.com", "site_name": "eBay", "category": "E-commerce", "tos_url": ""},
    {"url": "quora.com", "site_name": "Quora", "category": "Question and Answer", "tos_url": ""},
    {"url": "microsoftonline.com", "site_name": "Microsoft Online Services", "category": "Web Services", "tos_url": ""},
    {"url": "walmart.com", "site_name": "Walmart", "category": "E-commerce", "tos_url": ""},
    {"url": "linkedin.com", "site_name": "LinkedIn", "category": "Professional Networking", "tos_url": ""},
    {"url": "office.com", "site_name": "Office", "category": "Productivity Software", "tos_url": ""},
    {"url": "imdb.com", "site_name": "IMDb", "category": "Movies and TV", "tos_url": ""},
    {"url": "openai.com", "site_name": "OpenAI", "category": "Artificial Intelligence", "tos_url": ""},
    {"url": "live.com", "site_name": "Outlook (Live)", "category": "Web Services", "tos_url": ""},
    {"url": "twitch.tv", "site_name": "Twitch", "category": "Live Streaming", "tos_url": ""},
    {"url": "microsoft.com", "site_name": "Microsoft", "category": "Technology", "tos_url": ""},
    {"url": "usps.com", "site_name": "United States Postal Service", "category": "Postal Service", "tos_url": ""},
    {"url": "dailymail.co.uk", "site_name": "Daily Mail", "category": "News", "tos_url": ""},
    {"url": "netflix.com", "site_name": "Netflix", "category": "Streaming Service", "tos_url": ""},
    {"url": "msn.com", "site_name": "MSN", "category": "News and Services", "tos_url": ""},
    {"url": "etsy.com", "site_name": "Etsy", "category": "E-commerce", "tos_url": ""},
    {"url": "instructure.com", "site_name": "Instructure", "category": "Education Technology", "tos_url": ""},
    {"url": "paypal.com", "site_name": "PayPal", "category": "Payment Service", "tos_url": ""},
    {"url": "bestbuy.com", "site_name": "Best Buy", "category": "E-commerce", "tos_url": ""},
    {"url": "zoom.us", "site_name": "Zoom", "category": "Video Conferencing", "tos_url": ""},
    {"url": "nypost.com", "site_name": "New York Post", "category": "News", "tos_url": ""},
    {"url": "accuweather.com", "site_name": "AccuWeather", "category": "Weather", "tos_url": ""},
    {"url": "pinterest.com", "site_name": "Pinterest", "category": "Social Networking", "tos_url": ""},
    {"url": "indeed.com", "site_name": "Indeed", "category": "Job Search", "tos_url": ""},
    {"url": "zillow.com", "site_name": "Zillow", "category": "Real Estate", "tos_url": ""},
    {"url": "apple.com", "site_name": "Apple", "category": "Technology", "tos_url": ""},
    {"url": "homedepot.com", "site_name": "Home Depot", "category": "E-commerce", "tos_url": ""},
    {"url": "discord.com", "site_name": "Discord", "category": "Social Networking", "tos_url": ""},
    {"url": "bbc.com", "site_name": "BBC", "category": "News", "tos_url": ""},
    {"url": "ign.com", "site_name": "IGN", "category": "Gaming News", "tos_url": ""},
    {"url": "ups.com", "site_name": "UPS", "category": "Postal Service", "tos_url": ""},
    {"url": "sharepoint.com", "site_name": "SharePoint", "category": "Document Management", "tos_url": ""},
    {"url": "target.com", "site_name": "Target", "category": "E-commerce", "tos_url": ""},
    {"url": "imgur.com", "site_name": "Imgur", "category": "Image Sharing", "tos_url": ""},
    {"url": "craigslist.org", "site_name": "Craigslist", "category": "Classifieds", "tos_url": ""},
    {"url": "spotify.com", "site_name": "Spotify", "category": "Music Streaming", "tos_url": ""},
    {"url": "fedex.com", "site_name": "FedEx", "category": "Postal Service", "tos_url": ""},
    {"url": "amazonaws.com", "site_name": "Amazon Web Services", "category": "Cloud Computing", "tos_url": ""},
    {"url": "gamespot.com", "site_name": "GameSpot", "category": "Gaming News", "tos_url": ""},
    {"url": "breitbart.com", "site_name": "Breitbart", "category": "News", "tos_url": ""},
    {"url": "patreon.com", "site_name": "Patreon", "category": "Crowdfunding", "tos_url": ""},
    {"url": "washingtonpost.com", "site_name": "The Washington Post", "category": "News", "tos_url": ""},
    {"url": "hulu.com", "site_name": "Hulu", "category": "Streaming Service", "tos_url": ""},
    {"url": "theguardian.com", "site_name": "The Guardian", "category": "News", "tos_url": ""},
    {"url": "costco.com", "site_name": "Costco", "category": "E-commerce", "tos_url": ""},
    {"url": "chase.com", "site_name": "Chase", "category": "Banking", "tos_url": ""},
    {"url": "steamcommunity.com", "site_name": "Steam Community", "category": "Gaming Community", "tos_url": ""},
    {"url": "outlook.com", "site_name": "Outlook", "category": "Email Service", "tos_url": ""},
    {"url": "slickdeals.net", "site_name": "Slickdeals", "category": "Coupons and Deals", "tos_url": ""},
    {"url": "roblox.com", "site_name": "Roblox", "category": "Online Gaming Platform", "tos_url": ""},
    {"url": "github.com", "site_name": "GitHub", "category": "Software Development", "tos_url": ""},
    {"url": "usatoday.com", "site_name": "USA Today", "category": "News", "tos_url": ""},
    {"url": "samsung.com", "site_name": "Samsung", "category": "Electronics", "tos_url": ""},
    {"url": "character.ai", "site_name": "Character.AI", "category": "Artificial Intelligence", "tos_url": ""},
    {"url": "capitalone.com", "site_name": "Capital One", "category": "Banking", "tos_url": ""},
    {"url": "temu.com", "site_name": "Temu", "category": "E-commerce", "tos_url": ""},
    {"url": "nextdoor.com", "site_name": "Nextdoor", "category": "Social Networking", "tos_url": ""},
    {"url": "lowes.com", "site_name": "Lowe's", "category": "Home Improvement", "tos_url": ""},
    {"url": "nih.gov", "site_name": "National Institutes of Health (NIH)", "category": "Health", "tos_url": ""},
    {"url": "yelp.com", "site_name": "Yelp", "category": "Business Reviews", "tos_url": ""},
    {"url": "foxbusiness.com", "site_name": "Fox Business", "category": "Business News", "tos_url": ""},
    {"url": "npr.org", "site_name": "NPR", "category": "Public Radio", "tos_url": ""},
    {"url": "canva.com", "site_name": "Canva", "category": "Graphic Design", "tos_url": ""},
    {"url": "xfinity.com", "site_name": "Xfinity", "category": "Telecommunications", "tos_url": ""},
    {"url": "quizlet.com", "site_name": "Quizlet", "category": "Education", "tos_url": ""},
    {"url": "steampowered.com", "site_name": "Steam", "category": "Digital Distribution", "tos_url": ""},
    {"url": "okta.com", "site_name": "Okta", "category": "Identity Management", "tos_url": ""},
    {"url": "nbcnews.com", "site_name": "NBC News", "category": "News", "tos_url": ""},
    {"url": "cnbc.com", "site_name": "CNBC", "category": "Business News", "tos_url": ""},
    {"url": "apnews.com", "site_name": "Associated Press News", "category": "News Agency", "tos_url": ""},
    {"url": "adobe.com", "site_name": "Adobe", "category": "Software", "tos_url": ""},
    {"url": "cvs.com", "site_name": "CVS", "category": "Pharmacy", "tos_url": ""},
    {"url": "wordpress.com", "site_name": "WordPress", "category": "Web Publishing", "tos_url": ""},
    {"url": "whatsapp.com", "site_name": "WhatsApp", "category": "Messaging", "tos_url": ""}
]

# Insert data into the websites table 


# Insert data into the terms_of_service table