version: '3.8'

services:
  api:
    build: .
    container_name: api_service
    ports:
      - "3000:3000" # Map port 3000 on the host to port 3000 in the container
    environment:
      NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GOOGLE_SEARCH_API_KEY: ${GOOGLE_SEARCH_API_KEY}
    volumes:
      - .:/app
    command: npm run start # Adjust this command based on how you start your application

networks:
  default:
    external:
      name: my_network # Replace with your network name if needed